export const ERROR_CODES = {
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',
    UNAUTHORIZED: 'UNAUTHORIZED',
    TOKEN_MISSING: 'TOKEN_MISSING',
    TOKEN_INVALID: 'TOKEN_INVALID',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    OTP_RATE_LIMIT: 'OTP_RATE_LIMIT',
    OTP_NOT_FOUND: 'OTP_NOT_FOUND',
    OTP_EXPIRED: 'OTP_EXPIRED',
    OTP_INVALID: 'OTP_INVALID',
    RESET_TOKEN_INVALID: 'RESET_TOKEN_INVALID',
    RESET_TOKEN_USED: 'RESET_TOKEN_USED',
    RESET_TOKEN_EXPIRED: 'RESET_TOKEN_EXPIRED'
};
